spring.application.name=javis2
server.port=8080

# Flask AI 서버 주소
ai.server.url=http://localhost:5000

#Database 설정
#your_db_name, username, password는 실제 설정하신 값으로 변경하세요!
spring.datasource.url=jdbc:postgresql://localhost:3300/javis2
spring.datasource.username=postgres
spring.datasource.password=ekagus
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# pgvector와 원활한 통신을 위한 Dialect 설정
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 파일 업로드 제한 (PDF 등 문서 처리용)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB